<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockMode>LockModeFilePathAndContent</NuGetLockMode>
    <AssemblyName>SteamService</AssemblyName>
    <RootNamespace>SteamService</RootNamespace>
    <Product>MyWallpaperX</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SteamKit2" Version="3.4.0" />
  </ItemGroup>
</Project>
